### ISSUE TITLE
Z-index refactoring

### ISSUE THREAD

**Issue by ivanpopelyshev** [rpgtkoolmv/corescript#4]
This plugin (https://github.com/pixijs/pixi-display/tree/layers) allows to arrange z-indices without re-ordering of containers, regardless of the actual structure of the tree.

Demo: http://pixijs.github.io/examples/#/layers/lighting.js

**Comment by ghost** [comment]
Great plugin, but MV's Plugin compatibility is our high priority concern.
We have to be careful to breaking change.

What is pros and cons if we use this plugin?
I think we don't need changing algorithm.

**Comment by holywyvern** [comment]
So, in other words, this is what we used to call a Viewport on RPG Maker XP - VXA ?

That was something I like of the ruby versions...

**Comment by ghost** [comment]
PIXI has no camera (because It can be done with Container). so Viewport feature is missing.
Sorting all children sometimes causes performance problem. so We have to investigate about this.

In my experience, rewriting sorting algorithm to 'Insertion Sort' works great, but I'm not sure It works every use case.

I'll PR later. It needs review.
